//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class CrmPages_Admin_Customization_SiteMap_SiteMapAreaEdit {
    
    /// <summary>
    /// form1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    /// <summary>
    /// RR control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RegisterResources RR;
    
    /// <summary>
    /// SiteMapAreaId control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Hidden SiteMapAreaId;
    
    /// <summary>
    /// PanelX1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.PanelX PanelX1;
    
    /// <summary>
    /// ColumnLayout1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ColumnLayout ColumnLayout1;
    
    /// <summary>
    /// RowLayout1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout1;
    
    /// <summary>
    /// SiteMap control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ComboField SiteMap;
    
    /// <summary>
    /// SiteMapAreaLabelName control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.TextField SiteMapAreaLabelName;
    
    /// <summary>
    /// SiteMapAreaHref control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.TextField SiteMapAreaHref;
    
    /// <summary>
    /// SiteMapAreaDisplayOrder control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.TextField SiteMapAreaDisplayOrder;
    
    /// <summary>
    /// ColumnLayout2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ColumnLayout ColumnLayout2;
    
    /// <summary>
    /// RowLayout2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout2;
    
    /// <summary>
    /// ParentSiteMapArea control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ComboField ParentSiteMapArea;
    
    /// <summary>
    /// EntityList control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ComboField EntityList;
    
    /// <summary>
    /// PriEntityList control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ComboField PriEntityList;
    
    /// <summary>
    /// ImageHref control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.TextField ImageHref;
    
    /// <summary>
    /// New control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Button New;
    
    /// <summary>
    /// Save control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Button Save;
    
    /// <summary>
    /// Delete control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Button Delete;
    
    /// <summary>
    /// TreeGrid1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.TreeGrid TreeGrid1;
}
