//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Sender_CorporateAccountSender {
    
    /// <summary>
    /// form1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    /// <summary>
    /// RR control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RegisterResources RR;
    
    /// <summary>
    /// hdnSorguRefNo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Hidden hdnSorguRefNo;
    
    /// <summary>
    /// hdnSenderId control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Hidden hdnSenderId;
    
    /// <summary>
    /// FieldsetSenderInfo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Fieldset FieldsetSenderInfo;
    
    /// <summary>
    /// ColumnLayout3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ColumnLayout ColumnLayout3;
    
    /// <summary>
    /// RowLayout3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout3;
    
    /// <summary>
    /// new_MersisNumber control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmTextFieldComp new_MersisNumber;
    
    /// <summary>
    /// RowLayout12 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout12;
    
    /// <summary>
    /// Sender control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmTextFieldComp Sender;
    
    /// <summary>
    /// RowLayout19 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout19;
    
    /// <summary>
    /// ColumnLayout1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ColumnLayout ColumnLayout1;
    
    /// <summary>
    /// RowLayout20 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout20;
    
    /// <summary>
    /// btnCorporationFind control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Button btnCorporationFind;
    
    /// <summary>
    /// ColumnLayout2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ColumnLayout ColumnLayout2;
    
    /// <summary>
    /// RowLayout21 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout21;
    
    /// <summary>
    /// Button1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Button Button1;
    
    /// <summary>
    /// ColumnLayout4 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ColumnLayout ColumnLayout4;
    
    /// <summary>
    /// RowLayout4 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout4;
    
    /// <summary>
    /// new_RegistryNumber control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmTextFieldComp new_RegistryNumber;
    
    /// <summary>
    /// RowLayout1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout1;
    
    /// <summary>
    /// new_SenderIdendificationNumber1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmTextFieldComp new_SenderIdendificationNumber1;
    
    /// <summary>
    /// RowLayout2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout2;
    
    /// <summary>
    /// new_TaxNo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmTextFieldComp new_TaxNo;
    
    /// <summary>
    /// windowTuzelInfo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Window windowTuzelInfo;
    
    /// <summary>
    /// PanelX1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.PanelX PanelX1;
    
    /// <summary>
    /// ColumnLayout6 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ColumnLayout ColumnLayout6;
    
    /// <summary>
    /// RowLayout5 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout5;
    
    /// <summary>
    /// ColumnLayout7 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ColumnLayout ColumnLayout7;
    
    /// <summary>
    /// RowLayout7 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout7;
    
    /// <summary>
    /// SenderInfo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmTextFieldComp SenderInfo;
    
    /// <summary>
    /// RowLayout14 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout14;
    
    /// <summary>
    /// new_MersisNumberInfo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmTextFieldComp new_MersisNumberInfo;
    
    /// <summary>
    /// RowLayout9 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout9;
    
    /// <summary>
    /// new_CompanyNeviGrupInfo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmTextFieldComp new_CompanyNeviGrupInfo;
    
    /// <summary>
    /// RowLayout10 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout10;
    
    /// <summary>
    /// new_CompanyLegalStatusInfo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmTextFieldComp new_CompanyLegalStatusInfo;
    
    /// <summary>
    /// RowLayout16 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout16;
    
    /// <summary>
    /// new_TradeRegistryOfficeNameInfo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmTextFieldComp new_TradeRegistryOfficeNameInfo;
    
    /// <summary>
    /// RowLayout17 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout17;
    
    /// <summary>
    /// new_TradeRegistryOfficeCode control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmTextFieldComp new_TradeRegistryOfficeCode;
    
    /// <summary>
    /// RowLayout18 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout18;
    
    /// <summary>
    /// new_TradeRegistryOfficeCity control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmTextFieldComp new_TradeRegistryOfficeCity;
    
    /// <summary>
    /// ColumnLayout8 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ColumnLayout ColumnLayout8;
    
    /// <summary>
    /// RowLayout15 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout15;
    
    /// <summary>
    /// new_SenderIdendificationNumber1Info control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmTextFieldComp new_SenderIdendificationNumber1Info;
    
    /// <summary>
    /// RowLayout6 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout6;
    
    /// <summary>
    /// new_TaxNoInfo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmTextFieldComp new_TaxNoInfo;
    
    /// <summary>
    /// RowLayout13 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout13;
    
    /// <summary>
    /// new_TaxOfficeInfo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmTextFieldComp new_TaxOfficeInfo;
    
    /// <summary>
    /// RowLayout8 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout8;
    
    /// <summary>
    /// new_RegistryNumberInfo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmTextFieldComp new_RegistryNumberInfo;
    
    /// <summary>
    /// RowLayout11 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout11;
    
    /// <summary>
    /// new_RegistrationDateInfo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmDateFieldComp new_RegistrationDateInfo;
    
    /// <summary>
    /// btnSaveCustomer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Button btnSaveCustomer;
    
    /// <summary>
    /// btnGoCustomer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Button btnGoCustomer;
    
    /// <summary>
    /// btnUpdateCustomer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Button btnUpdateCustomer;
}
