//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Sender_SenderSegmentation {
    
    /// <summary>
    /// form1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    /// <summary>
    /// KeyMap1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.KeyMap KeyMap1;
    
    /// <summary>
    /// KeyMap2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.KeyMap KeyMap2;
    
    /// <summary>
    /// hdnViewList control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Hidden hdnViewList;
    
    /// <summary>
    /// hdnViewListTotal control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Hidden hdnViewListTotal;
    
    /// <summary>
    /// hdnViewDefaultEditPage control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Hidden hdnViewDefaultEditPage;
    
    /// <summary>
    /// nHdnSelectedRowId control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Hidden nHdnSelectedRowId;
    
    /// <summary>
    /// RR control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RegisterResources RR;
    
    /// <summary>
    /// pnl1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.PanelX pnl1;
    
    /// <summary>
    /// ColoumnLayout1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ColumnLayout ColoumnLayout1;
    
    /// <summary>
    /// RowLayout1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout1;
    
    /// <summary>
    /// new_SenderId control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmComboComp new_SenderId;
    
    /// <summary>
    /// ColumnLayout1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ColumnLayout ColumnLayout1;
    
    /// <summary>
    /// RowLayout4 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout4;
    
    /// <summary>
    /// new_SenderSegmentationId control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmComboComp new_SenderSegmentationId;
    
    /// <summary>
    /// ColumnLayout2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ColumnLayout ColumnLayout2;
    
    /// <summary>
    /// RowLayout2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout2;
    
    /// <summary>
    /// new_SenderNumber control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmTextFieldComp new_SenderNumber;
    
    /// <summary>
    /// ToolbarButtonFind control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Button ToolbarButtonFind;
    
    /// <summary>
    /// ToolbarButtonClear control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Button ToolbarButtonClear;
    
    /// <summary>
    /// GridPanelMonitoring control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.GridPanel GridPanelMonitoring;
    
    /// <summary>
    /// ToolButton1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ToolButton ToolButton1;
    
    /// <summary>
    /// GridPanelMonitoringRowSelectionModel1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowSelectionModel GridPanelMonitoringRowSelectionModel1;
    
    /// <summary>
    /// PagingToolBar1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.PagingToolBar PagingToolBar1;
    
    /// <summary>
    /// btnDownload control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.SmallButton btnDownload;
    
    /// <summary>
    /// BtnSb1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.SmallButton BtnSb1;
    
    /// <summary>
    /// WindowEdit control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Window WindowEdit;
    
    /// <summary>
    /// PanelX1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.PanelX PanelX1;
    
    /// <summary>
    /// ColumnLayout3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ColumnLayout ColumnLayout3;
    
    /// <summary>
    /// RowLayout3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout3;
    
    /// <summary>
    /// nSender control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmComboComp nSender;
    
    /// <summary>
    /// nSenderSegmentationId control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmComboComp nSenderSegmentationId;
    
    /// <summary>
    /// btnSave control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Button btnSave;
    
    /// <summary>
    /// windowImport control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Window windowImport;
    
    /// <summary>
    /// PanelX2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.PanelX PanelX2;
    
    /// <summary>
    /// ColumnLayout4 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ColumnLayout ColumnLayout4;
    
    /// <summary>
    /// RowLayout5 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout5;
    
    /// <summary>
    /// ExcelFileUpload control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.FileUpload ExcelFileUpload;
    
    /// <summary>
    /// ButtonTemplate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Button ButtonTemplate;
    
    /// <summary>
    /// btnUpload control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Button btnUpload;
}
