//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class FreeAccounting_ManuelAbAccounting {
    
    /// <summary>
    /// Head1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlHead Head1;
    
    /// <summary>
    /// form1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    /// <summary>
    /// RR control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RegisterResources RR;
    
    /// <summary>
    /// TransferId control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Hidden TransferId;
    
    /// <summary>
    /// PaymentId control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Hidden PaymentId;
    
    /// <summary>
    /// RefundpaymentId control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Hidden RefundpaymentId;
    
    /// <summary>
    /// TransferReference control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Hidden TransferReference;
    
    /// <summary>
    /// TransactionType control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Hidden TransactionType;
    
    /// <summary>
    /// pnl1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.PanelX pnl1;
    
    /// <summary>
    /// ColumnLayout3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ColumnLayout ColumnLayout3;
    
    /// <summary>
    /// RowLayout4 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout4;
    
    /// <summary>
    /// ColoumnLayout1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ColumnLayout ColoumnLayout1;
    
    /// <summary>
    /// RowLayout1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout1;
    
    /// <summary>
    /// TransferTuRef control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmTextFieldComp TransferTuRef;
    
    /// <summary>
    /// ColumnLayout2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ColumnLayout ColumnLayout2;
    
    /// <summary>
    /// RowLayout5 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout5;
    
    /// <summary>
    /// btnControl control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Button btnControl;
    
    /// <summary>
    /// ColumnLayout232 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ColumnLayout ColumnLayout232;
    
    /// <summary>
    /// RowLayout8 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout8;
    
    /// <summary>
    /// OperationType control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ComboField OperationType;
    
    /// <summary>
    /// ColumnLayout1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ColumnLayout ColumnLayout1;
    
    /// <summary>
    /// RowLayout9 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout9;
    
    /// <summary>
    /// Button1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.Button Button1;
    
    /// <summary>
    /// RowLayout4232 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout4232;
    
    /// <summary>
    /// RowLayout7 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout7;
    
    /// <summary>
    /// ColumnLayout12 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.ColumnLayout ColumnLayout12;
    
    /// <summary>
    /// RowLayout3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout3;
    
    /// <summary>
    /// GrdTransfer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.GridPanel GrdTransfer;
    
    /// <summary>
    /// RowSelectionModel2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowSelectionModel RowSelectionModel2;
    
    /// <summary>
    /// RowLayout33 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout33;
    
    /// <summary>
    /// RowLayout2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout2;
    
    /// <summary>
    /// GrdPayment control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.GridPanel GrdPayment;
    
    /// <summary>
    /// RowSelectionModel1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowSelectionModel RowSelectionModel1;
    
    /// <summary>
    /// RowLayout34 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout34;
    
    /// <summary>
    /// RowLayout6 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowLayout RowLayout6;
    
    /// <summary>
    /// GrpRefundPayment control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.GridPanel GrpRefundPayment;
    
    /// <summary>
    /// RowSelectionModel3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::RefleXFrameWork.RowSelectionModel RowSelectionModel3;
}
