//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class CrmPages_AutoPages_LookUp {
    
    /// <summary>
    /// form1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    /// <summary>
    /// StoreViewer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.Store StoreViewer;
    
    /// <summary>
    /// ReferencedObjectId control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.Hidden ReferencedObjectId;
    
    /// <summary>
    /// LookupTextId control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.Hidden LookupTextId;
    
    /// <summary>
    /// LookupValueId control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.Hidden LookupValueId;
    
    /// <summary>
    /// ViewQuery control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.Hidden ViewQuery;
    
    /// <summary>
    /// FetchXML control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.Hidden FetchXML;
    
    /// <summary>
    /// ViewPort1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.ViewPort ViewPort1;
    
    /// <summary>
    /// FitLayout1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.FitLayout FitLayout1;
    
    /// <summary>
    /// GridPanelViewer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.GridPanel GridPanelViewer;
    
    /// <summary>
    /// Toolbar1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.Toolbar Toolbar1;
    
    /// <summary>
    /// FilterText control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.TriggerField FilterText;
    
    /// <summary>
    /// btnNew control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.Button btnNew;
    
    /// <summary>
    /// CmbPageSize control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.ComboBox CmbPageSize;
    
    /// <summary>
    /// gridsearch control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coretech.Crm.Web.UI.ExtPlugin.GridSearch gridsearch;
    
    /// <summary>
    /// RowSelectionModel1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.RowSelectionModel RowSelectionModel1;
    
    /// <summary>
    /// PagingToolBar1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.PagingToolbar PagingToolBar1;
}
