//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class CrmPages_Admin_Share_Share {
    
    /// <summary>
    /// form1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    /// <summary>
    /// hdnObjectId control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.Hidden hdnObjectId;
    
    /// <summary>
    /// hdnRecid control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.Hidden hdnRecid;
    
    /// <summary>
    /// StoreUser control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.Store StoreUser;
    
    /// <summary>
    /// StoreTeam control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.Store StoreTeam;
    
    /// <summary>
    /// Store1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.Store Store1;
    
    /// <summary>
    /// ViewPort1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.ViewPort ViewPort1;
    
    /// <summary>
    /// FitLayout1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.FitLayout FitLayout1;
    
    /// <summary>
    /// GridPanel1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.GridPanel GridPanel1;
    
    /// <summary>
    /// RowSelectionModel1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.RowSelectionModel RowSelectionModel1;
    
    /// <summary>
    /// toolbar1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.Toolbar toolbar1;
    
    /// <summary>
    /// btnSave control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.ToolbarButton btnSave;
    
    /// <summary>
    /// NewUser control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.ToolbarButton NewUser;
    
    /// <summary>
    /// NewTeam control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.ToolbarButton NewTeam;
    
    /// <summary>
    /// WindowUser control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.Window WindowUser;
    
    /// <summary>
    /// Add_User control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.ToolbarButton Add_User;
    
    /// <summary>
    /// FormPanel5 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.FormPanel FormPanel5;
    
    /// <summary>
    /// FormLayout8 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.FormLayout FormLayout8;
    
    /// <summary>
    /// UserCmp control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.ComboBox UserCmp;
    
    /// <summary>
    /// WindowTeam control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.Window WindowTeam;
    
    /// <summary>
    /// Toolbar2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.Toolbar Toolbar2;
    
    /// <summary>
    /// Add_Team control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.ToolbarButton Add_Team;
    
    /// <summary>
    /// FormPanel1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.FormPanel FormPanel1;
    
    /// <summary>
    /// FormLayout1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.FormLayout FormLayout1;
    
    /// <summary>
    /// TeamCmp control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Coolite.Ext.Web.ComboBox TeamCmp;
}
