//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reconciliation.Detail {
    
    
    public partial class Reconciliation_UptBankTotalCheck {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// KeyMap1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.KeyMap KeyMap1;
        
        /// <summary>
        /// RR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.RegisterResources RR;
        
        /// <summary>
        /// HdnReConciliationId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.Hidden HdnReConciliationId;
        
        /// <summary>
        /// HdnReportId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.Hidden HdnReportId;
        
        /// <summary>
        /// PanelX1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.PanelX PanelX1;
        
        /// <summary>
        /// ColoumnLayout1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.ColumnLayout ColoumnLayout1;
        
        /// <summary>
        /// RowLayout1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.RowLayout RowLayout1;
        
        /// <summary>
        /// new_StartDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmDateFieldComp new_StartDate;
        
        /// <summary>
        /// ColumnLayout3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.ColumnLayout ColumnLayout3;
        
        /// <summary>
        /// RowLayout32 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.RowLayout RowLayout32;
        
        /// <summary>
        /// new_EndDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmDateFieldComp new_EndDate;
        
        /// <summary>
        /// pnl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.PanelX pnl1;
        
        /// <summary>
        /// PanelX3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.Fieldset PanelX3;
        
        /// <summary>
        /// GrdTotalReConciliation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.GridPanel GrdTotalReConciliation;
        
        /// <summary>
        /// RowSelectionModel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.RowSelectionModel RowSelectionModel2;
        
        /// <summary>
        /// GetReConciliation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.Button GetReConciliation;
        
        /// <summary>
        /// btnExportToExcel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.Button btnExportToExcel;
        
        /// <summary>
        /// windowOpenReceipt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.Window windowOpenReceipt;
        
        /// <summary>
        /// PanelX2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.PanelX PanelX2;
        
        /// <summary>
        /// ColumnLayout8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.ColumnLayout ColumnLayout8;
        
        /// <summary>
        /// RowLayout8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.RowLayout RowLayout8;
        
        /// <summary>
        /// lblTransaction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.Label lblTransaction;
        
        /// <summary>
        /// PanelX4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.PanelX PanelX4;
        
        /// <summary>
        /// ColumnLayout1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.ColumnLayout ColumnLayout1;
        
        /// <summary>
        /// RowLayout2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.RowLayout RowLayout2;
        
        /// <summary>
        /// cfAction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.ComboField cfAction;
    }
}
