//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coretech.Crm.Web.ISV.TU.Corporated {
    
    
    public partial class CorporatedPreInfoStepCargo {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// RR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.RegisterResources RR;
        
        /// <summary>
        /// pnl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.PanelX pnl1;
        
        /// <summary>
        /// btnInformation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.ToolButton btnInformation;
        
        /// <summary>
        /// ColoumnLayout1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.ColumnLayout ColoumnLayout1;
        
        /// <summary>
        /// RowLayout10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.RowLayout RowLayout10;
        
        /// <summary>
        /// MultiField1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.MultiField MultiField1;
        
        /// <summary>
        /// new_CorparateName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmTextFieldComp new_CorparateName;
        
        /// <summary>
        /// RowLayout1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.RowLayout RowLayout1;
        
        /// <summary>
        /// mfsender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.MultiField mfsender;
        
        /// <summary>
        /// new_CorparateCentralRegistryServiceNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmTextFieldComp new_CorparateCentralRegistryServiceNumber;
        
        /// <summary>
        /// RowLayout101 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.RowLayout RowLayout101;
        
        /// <summary>
        /// new_New_CorporatedType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmComboComp new_New_CorporatedType;
        
        /// <summary>
        /// RowLayout2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.RowLayout RowLayout2;
        
        /// <summary>
        /// new_StatusId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmPicklistComp new_StatusId;
        
        /// <summary>
        /// RowLayout6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.RowLayout RowLayout6;
        
        /// <summary>
        /// MultiField5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.MultiField MultiField5;
        
        /// <summary>
        /// new_CorparateCentralRegistryServiceQueryRefNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmTextFieldComp new_CorparateCentralRegistryServiceQueryRefNumber;
        
        /// <summary>
        /// ColumnLayout1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.ColumnLayout ColumnLayout1;
        
        /// <summary>
        /// RowLayout5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.RowLayout RowLayout5;
        
        /// <summary>
        /// MultiField4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.MultiField MultiField4;
        
        /// <summary>
        /// new_CorparateTaxNo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmTextFieldComp new_CorparateTaxNo;
        
        /// <summary>
        /// RowLayout3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.RowLayout RowLayout3;
        
        /// <summary>
        /// MultiField2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.MultiField MultiField2;
        
        /// <summary>
        /// new_MobilePhone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmTextFieldComp new_MobilePhone;
        
        /// <summary>
        /// RowLayout4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.RowLayout RowLayout4;
        
        /// <summary>
        /// MultiField3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.MultiField MultiField3;
        
        /// <summary>
        /// new_EMail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmTextFieldComp new_EMail;
        
        /// <summary>
        /// RowLayout7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.RowLayout RowLayout7;
        
        /// <summary>
        /// MultiField6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.MultiField MultiField6;
        
        /// <summary>
        /// new_NationalityId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmComboComp new_NationalityId;
        
        /// <summary>
        /// RowLayout8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.RowLayout RowLayout8;
        
        /// <summary>
        /// MultiField7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.MultiField MultiField7;
        
        /// <summary>
        /// new_HomeCountryId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coretech.Crm.Web.UI.RefleX.AutoGenerate.CrmComboComp new_HomeCountryId;
        
        /// <summary>
        /// hdnRecId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.Hidden hdnRecId;
        
        /// <summary>
        /// documentId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.Hidden documentId;
        
        /// <summary>
        /// documentName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.Hidden documentName;
        
        /// <summary>
        /// hdnUploaded control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.Hidden hdnUploaded;
        
        /// <summary>
        /// hdnStatusId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.Hidden hdnStatusId;
        
        /// <summary>
        /// PanelX1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.PanelX PanelX1;
        
        /// <summary>
        /// ColumnLayout12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.ColumnLayout ColumnLayout12;
        
        /// <summary>
        /// RowLayout9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.RowLayout RowLayout9;
        
        /// <summary>
        /// lblDocumentName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.Label lblDocumentName;
        
        /// <summary>
        /// RowLayout11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.RowLayout RowLayout11;
        
        /// <summary>
        /// mfFileSys control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.MultiField mfFileSys;
        
        /// <summary>
        /// senderDocumentFile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.FileUpload senderDocumentFile;
        
        /// <summary>
        /// lbl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.Label lbl1;
        
        /// <summary>
        /// BtnUpload control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.Button BtnUpload;
        
        /// <summary>
        /// btnAccept control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RefleXFrameWork.Button btnAccept;
    }
}
